/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalculadoraSimple;

import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;

/**
 *
 * @author ruben
 */
public class GUI extends javax.swing.JFrame {
float a=0,b=0;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Resultado = new javax.swing.JLabel();
        numA = new javax.swing.JTextField();
        numB = new javax.swing.JTextField();
        op = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        op.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/" }));
        op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Resultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(numA, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(numB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opActionPerformed
        if(op.getSelectedItem().equals("+")){
            try{
                Registry reg = LocateRegistry.getRegistry("127.0.0.1",1099);
                RMIOperaciones rmio;
                rmio = (RMIOperaciones)reg.lookup("Objeto Remoto");
                a = (float) Double.parseDouble(numA.getText());
                b = (float) Double.parseDouble(numB.getText());
                Resultado.setText(""+rmio.sumar(a, b));

            }catch(RemoteException re){
                re.printStackTrace();
            } catch (NotBoundException ex) {
                ex.printStackTrace();
            } catch(NumberFormatException nfe){
                Resultado.setText(nfe.getMessage());
            }
        }
        if(op.getSelectedItem().equals("-")){
            try{
                Registry reg = LocateRegistry.getRegistry("127.0.0.1",1099);
                RMIOperaciones rmio;
                rmio = (RMIOperaciones)reg.lookup("Objeto Remoto");
                a = (float) Double.parseDouble(numA.getText());
                b = (float) Double.parseDouble(numB.getText());
                Resultado.setText(""+rmio.restar(a, b));

            }catch(RemoteException re){
                re.printStackTrace();
            } catch (NotBoundException ex) {
                ex.printStackTrace();
            } catch(NumberFormatException nfe){
                Resultado.setText(nfe.getMessage());
            }
        }
          if(op.getSelectedItem().equals("*")){
            try{
                Registry reg = LocateRegistry.getRegistry("127.0.0.1",1099);
                RMIOperaciones rmio;
                rmio = (RMIOperaciones)reg.lookup("Objeto Remoto");
                a = (float) Double.parseDouble(numA.getText());
                b = (float) Double.parseDouble(numB.getText());
                Resultado.setText(""+rmio.multiplicar(a, b));

            }catch(RemoteException re){
                re.printStackTrace();
            } catch (NotBoundException ex) {
                ex.printStackTrace();
            } catch(NumberFormatException nfe){
                Resultado.setText(nfe.getMessage());
            }
        }
            if(op.getSelectedItem().equals("/")){
            try{
                Registry reg = LocateRegistry.getRegistry("127.0.0.1",1099);
                RMIOperaciones rmio;
                rmio = (RMIOperaciones)reg.lookup("Objeto Remoto");
                a = (float) Double.parseDouble(numA.getText());
                b = (float) Double.parseDouble(numB.getText());
                Resultado.setText(""+rmio.dividir(a, b));

            }catch(RemoteException re){
                re.printStackTrace();
            } catch (NotBoundException ex) {
                ex.printStackTrace();
            } catch(NumberFormatException nfe){
                Resultado.setText(nfe.getMessage());
            }
        }

    }//GEN-LAST:event_opActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Resultado;
    private javax.swing.JTextField numA;
    private javax.swing.JTextField numB;
    private javax.swing.JComboBox<String> op;
    // End of variables declaration//GEN-END:variables
}
